development:
  adapter: postgresql
  encoding: utf8
  database: overflow_clone_development
  username: maxc
  password: '123'
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: overflow_clone_test
  username: maxc
  password: '123'
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: overflow_clone_production
  username: maxc
  password: '123'
  host: localhost


